# Generated by Django 5.0.6 on 2024-07-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponddata',
            name='aerator_status',
            field=models.BooleanField(default=False),
        ),
    ]
