# Generated by Django 5.0.6 on 2024-07-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_ponddata_aerator_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ponddata',
            old_name='pH',
            new_name='ph',
        ),
    ]
