# Generated by Django 5.0.6 on 2024-07-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_rename_ph_ponddata_ph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeratorstatus',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='ponddata',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='pondnote',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
