# Generated by Django 5.0.6 on 2024-07-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_aeratorstatus_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeratorstatus',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='ponddata',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pondnote',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
    ]
