# Generated by Django 5.0.6 on 2024-07-10 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_alter_aeratorstatus_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponddata',
            name='aerator_status',
        ),
        migrations.AlterField(
            model_name='aeratorstatus',
            name='phone_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitoring.user'),
        ),
        migrations.AlterField(
            model_name='ponddata',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='pondnote',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
