# Generated by Django 5.0.6 on 2024-07-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_remove_ponddata_aerator_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeratorstatus',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
